name: fitable
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  easy_localization: ^3.0.0
  easy_localization_loader: ^1.0.0
  url_strategy: ^0.2.0

  flutter_bloc: ^8.0.1
  hydrated_bloc: ^8.1.0
  hive: ^2.0.6
  get_it: ^7.2.0
  injectable: ^1.5.3
  rxdart: ^0.27.3
  dartz: ^0.10.1
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  auto_route: ^3.2.4

  appwrite: ^4.0.1
#  google_sign_in: ^5.1.1
#  firebase_core: ^1.7.0
#  firebase_analytics: ^8.3.3
#  firebase_crashlytics: ^2.2.4

#  firebase_messaging: ^10.0.9
#  firebase_in_app_messaging: ^0.5.0+11

#  firebase_auth: ^3.1.2
#  cloud_firestore: ^2.5.3
#  firebase_storage: ^10.0.4

  connectivity_plus: ^2.2.1
  validators: ^3.0.0
  dio: ^4.0.4

  font_awesome_flutter: ^9.2.0
  responsive_framework: ^0.1.7
  google_fonts: ^2.3.1
  cupertino_icons: ^1.0.4

  cached_network_image: ^3.2.0
  crop_your_image: ^0.7.2
  image_picker: ^0.8.4+11

  introduction_screen: ^3.0.0
  auto_size_text: ^3.0.0
  flutter_spinkit: ^5.1.0
  smooth_page_indicator: ^1.0.0+2
  bot_toast: ^4.0.1
  checklist: ^0.1.4
  flutter_picker: ^2.0.3

#  google_mobile_ads: ^0.11.0+1
#  facebook_audience_network: ^0.9.0
#  in_app_purchase: ^1.0.0

#  health: 3.0.4
#  qrscan: ^0.3.1
  uuid: ^3.0.6
  barcode_widget: ^2.0.2
  youtube_player_iframe: ^2.2.2
  smooth_star_rating: ^1.1.1

dev_dependencies:
#  flutter_test:
#    sdk: flutter
#  integration_test:
#    sdk: flutter

#  test: ^1.20.1
#  bloc_test: ^9.0.2

  lints: ^1.0.1
  flutter_lints: ^1.0.4
  build_runner: ^2.1.8
  injectable_generator: ^1.5.3
  auto_route_generator: ^3.2.3
  freezed: ^1.1.1
  json_serializable: ^6.1.5
  logger: ^1.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/