name: fitable
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  url_strategy: ^0.2.0
  flutter_bloc: ^8.0.1
  hydrated_bloc: ^9.0.0-dev.2
  hive: ^2.1.0
  get_it: ^7.2.0
  injectable: ^1.5.3
  rxdart: ^0.27.3
  dartz: ^0.10.1
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  auto_route: ^3.2.4

  appwrite: ^4.0.2
  connectivity_plus: ^2.3.0
  validators: ^3.0.0
  dio: ^4.0.6
  logger: ^1.1.0

  font_awesome_flutter: ^10.1.0
  responsive_framework: ^0.1.7
  google_fonts: ^2.3.1
  cupertino_icons: ^1.0.4

  cached_network_image: ^3.2.0
  crop_your_image: ^0.7.2
  image_picker: ^0.8.5

  introduction_screen: ^3.0.2
  drag_and_drop_lists: ^0.3.2+2
  auto_size_text: ^3.0.0
  flutter_spinkit: ^5.1.0
  smooth_page_indicator: ^1.0.0+2
  bot_toast: ^4.0.1
  flutter_picker: ^2.0.3
  drop_down_list: ^0.0.2
  badges: ^2.0.2
  
  uuid: ^3.0.6
  barcode_widget: ^2.0.2
  youtube_player_iframe: ^2.2.2
  flutter_rating_bar: ^4.0.0

  flutter_barcode_scanner: ^2.0.0
  health: ^3.4.4

  flutter_services_binding: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any
  bloc_test: ^9.0.3
  flutter_lints: ^1.0.4
  build_runner: ^2.1.8
  injectable_generator: ^1.5.2
  auto_route_generator: ^3.2.3
  freezed: ^1.1.0
  json_serializable: ^6.1.5

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/images/