name: fitable
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.0
  easy_localization_loader: ^1.0.0

  firebase_core: ^1.0.3
  firebase_auth: ^1.1.0
  google_sign_in: ^5.0.2

  permission_handler: ^6.1.3
  flutter_riverpod: ^0.14.0+1

  cloud_firestore: ^1.0.5
  cloud_functions: ^1.0.3
  firebase_storage: ^8.0.3
  firebase_analytics: ^8.0.0

  firebase_in_app_messaging: ^0.5.0
  firebase_messaging: ^9.1.1

  algolia: ^1.0.1

#  google_mobile_ads: ^0.11.0+1
  facebook_audience_network: ^0.9.0
  in_app_purchase: ^0.5.2

  extended_image: ^4.0.1
  image: ^3.0.2
  file_picker: ^3.0.1

  health: ^3.0.5
  qrscan: ^0.3.1

  cached_network_image: ^3.0.0

  font_awesome_flutter: ^9.0.0
  google_fonts: ^2.0.0
  cupertino_icons: ^1.0.2

  introduction_screen: ^2.1.0

  youtube_player_iframe: ^2.0.0
  carousel_slider: ^3.0.0
  another_flushbar: ^1.10.17
  auto_size_text: ^2.1.0
  smooth_star_rating: ^1.1.1
  checklist: ^0.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  logger: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - resources/images/
    - resources/languages/
    - resources/
#    - resources/images/google-logo.png
#    - resources/images/facebook-logo.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
