// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'product_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_Product _$$_ProductFromJson(Map<String, dynamic> json) => _$_Product(
      id: json['id'] as String,
      barcode: json['barcode'] as String,
      name: json['name'] as String,
      categoryPrimary: json['categoryPrimary'] as String,
      categorySecondary: json['categorySecondary'] as String,
      localeBase: json['localeBase'] as String,
      keyWords:
          (json['keyWords'] as List<dynamic>).map((e) => e as String).toList(),
      portions:
          (json['portions'] as List<dynamic>).map((e) => e as String).toList(),
      verification: json['verification'] as bool,
      calories: json['calories'] as int,
      proteins: (json['proteins'] as num).toDouble(),
      carbs: (json['carbs'] as num).toDouble(),
      fats: (json['fats'] as num).toDouble(),
      dateCreation: DateTime.parse(json['dateCreation'] as String),
      dateLastUpdate: DateTime.parse(json['dateLastUpdate'] as String),
      photosUrl: json['photosUrl'] as String,
      sugar: (json['sugar'] as num).toDouble(),
      animalProteins: (json['animalProteins'] as num).toDouble(),
      plantProteins: (json['plantProteins'] as num).toDouble(),
      saturated: (json['saturated'] as num).toDouble(),
      unsaturated: (json['unsaturated'] as num).toDouble(),
      omega3: (json['omega3'] as num).toDouble(),
      omega6: (json['omega6'] as num).toDouble(),
      fiber: (json['fiber'] as num).toDouble(),
      caffeine: (json['caffeine'] as num).toDouble(),
      cholesterol: (json['cholesterol'] as num).toDouble(),
      salt: (json['salt'] as num).toDouble(),
      vitaminA: (json['vitaminA'] as num).toDouble(),
      vitaminC: (json['vitaminC'] as num).toDouble(),
      vitaminD: (json['vitaminD'] as num).toDouble(),
      vitaminE: (json['vitaminE'] as num).toDouble(),
      vitaminK: (json['vitaminK'] as num).toDouble(),
      vitaminB1: (json['vitaminB1'] as num).toDouble(),
      vitaminB2: (json['vitaminB2'] as num).toDouble(),
      vitaminB3: (json['vitaminB3'] as num).toDouble(),
      vitaminB5: (json['vitaminB5'] as num).toDouble(),
      vitaminB6: (json['vitaminB6'] as num).toDouble(),
      vitaminB7: (json['vitaminB7'] as num).toDouble(),
      vitaminB9: (json['vitaminB9'] as num).toDouble(),
      vitaminB12: (json['vitaminB12'] as num).toDouble(),
      potassium: (json['potassium'] as num).toDouble(),
      sodium: (json['sodium'] as num).toDouble(),
      calcium: (json['calcium'] as num).toDouble(),
      magnesium: (json['magnesium'] as num).toDouble(),
      phosphorus: (json['phosphorus'] as num).toDouble(),
      iron: (json['iron'] as num).toDouble(),
      copper: (json['copper'] as num).toDouble(),
      zinc: (json['zinc'] as num).toDouble(),
      selenium: (json['selenium'] as num).toDouble(),
      manganese: (json['manganese'] as num).toDouble(),
      iodine: (json['iodine'] as num).toDouble(),
      chromium: (json['chromium'] as num).toDouble(),
    );

Map<String, dynamic> _$$_ProductToJson(_$_Product instance) =>
    <String, dynamic>{
      'id': instance.id,
      'barcode': instance.barcode,
      'name': instance.name,
      'categoryPrimary': instance.categoryPrimary,
      'categorySecondary': instance.categorySecondary,
      'localeBase': instance.localeBase,
      'keyWords': instance.keyWords,
      'portions': instance.portions,
      'verification': instance.verification,
      'calories': instance.calories,
      'proteins': instance.proteins,
      'carbs': instance.carbs,
      'fats': instance.fats,
      'dateCreation': instance.dateCreation.toIso8601String(),
      'dateLastUpdate': instance.dateLastUpdate.toIso8601String(),
      'photosUrl': instance.photosUrl,
      'sugar': instance.sugar,
      'animalProteins': instance.animalProteins,
      'plantProteins': instance.plantProteins,
      'saturated': instance.saturated,
      'unsaturated': instance.unsaturated,
      'omega3': instance.omega3,
      'omega6': instance.omega6,
      'fiber': instance.fiber,
      'caffeine': instance.caffeine,
      'cholesterol': instance.cholesterol,
      'salt': instance.salt,
      'vitaminA': instance.vitaminA,
      'vitaminC': instance.vitaminC,
      'vitaminD': instance.vitaminD,
      'vitaminE': instance.vitaminE,
      'vitaminK': instance.vitaminK,
      'vitaminB1': instance.vitaminB1,
      'vitaminB2': instance.vitaminB2,
      'vitaminB3': instance.vitaminB3,
      'vitaminB5': instance.vitaminB5,
      'vitaminB6': instance.vitaminB6,
      'vitaminB7': instance.vitaminB7,
      'vitaminB9': instance.vitaminB9,
      'vitaminB12': instance.vitaminB12,
      'potassium': instance.potassium,
      'sodium': instance.sodium,
      'calcium': instance.calcium,
      'magnesium': instance.magnesium,
      'phosphorus': instance.phosphorus,
      'iron': instance.iron,
      'copper': instance.copper,
      'zinc': instance.zinc,
      'selenium': instance.selenium,
      'manganese': instance.manganese,
      'iodine': instance.iodine,
      'chromium': instance.chromium,
    };
