import 'package:freezed_annotation/freezed_annotation.dart';

import '../portions/portion_model.dart';

part 'product_model.freezed.dart';
part 'product_model.g.dart';

enum EnTypeLocale { pl, en }

@freezed
class Product with _$Product {
  const factory Product({
    required String id,
    required String barcode,
    required String name,
    required String categoryPrimary,
    required String categorySecondary,
    required EnTypeLocale localeBase,
    required List<String> keyWords,
    required List<Portion> portions,
    required bool verification,
    required int calories,
    required double proteins,
    required double carbs,
    required double fats,
    required DateTime dateCreation,
    required DateTime dateLastUpdate,
    required String photosUrl,
    required double sugar,
    required double animalProteins,
    required double plantProteins,
    required double saturated,
    required double unsaturated,
    required double omega3,
    required double omega6,
    required double fiber,
    required double caffeine,
    required double cholesterol,
    required double salt,
    required double vitaminA,
    required double vitaminC,
    required double vitaminD,
    required double vitaminE,
    required double vitaminK,
    required double vitaminB1,
    required double vitaminB2,
    required double vitaminB3,
    required double vitaminB5,
    required double vitaminB6,
    required double vitaminB7,
    required double vitaminB9,
    required double vitaminB12,
    required double potassium,
    required double sodium,
    required double calcium,
    required double magnesium,
    required double phosphorus,
    required double iron,
    required double copper,
    required double zinc,
    required double selenium,
    required double manganese,
    required double iodine,
    required double chromium,
  }) = _Product;

  const factory Product.buildEmpty({
    @Default('') String id,
    @Default('') String barcode,
    @Default('') String name,
    @Default('') String categoryPrimary,
    @Default('') String categorySecondary,
    @Default(EnTypeLocale.pl) EnTypeLocale localeBase,
    @Default(<String>[]) List<String> keyWords,
    @Default(<Portion>[]) List<Portion> portions,
    @Default(false) bool verification,
    @Default(0) int calories,
    @Default(0.0) double proteins,
    @Default(0.0) double carbs,
    @Default(0.0) double fats,
    required DateTime dateCreation,
    required DateTime dateLastUpdate,
    @Default('') String photosUrl,
    @Default(0.0) double sugar,
    @Default(0.0) double animalProteins,
    @Default(0.0) double plantProteins,
    @Default(0.0) double saturated,
    @Default(0.0) double unsaturated,
    @Default(0.0) double omega3,
    @Default(0.0) double omega6,
    @Default(0.0) double fiber,
    @Default(0.0) double caffeine,
    @Default(0.0) double cholesterol,
    @Default(0.0) double salt,
    @Default(0.0) double vitaminA,
    @Default(0.0) double vitaminC,
    @Default(0.0) double vitaminD,
    @Default(0.0) double vitaminE,
    @Default(0.0) double vitaminK,
    @Default(0.0) double vitaminB1,
    @Default(0.0) double vitaminB2,
    @Default(0.0) double vitaminB3,
    @Default(0.0) double vitaminB5,
    @Default(0.0) double vitaminB6,
    @Default(0.0) double vitaminB7,
    @Default(0.0) double vitaminB9,
    @Default(0.0) double vitaminB12,
    @Default(0.0) double potassium,
    @Default(0.0) double sodium,
    @Default(0.0) double calcium,
    @Default(0.0) double magnesium,
    @Default(0.0) double phosphorus,
    @Default(0.0) double iron,
    @Default(0.0) double copper,
    @Default(0.0) double zinc,
    @Default(0.0) double selenium,
    @Default(0.0) double manganese,
    @Default(0.0) double iodine,
    @Default(0.0) double chromium,
  }) = Build;

  factory Product.fromJson(Map<String, dynamic> json) => _$ProductFromJson(json);
}
